# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O3ljFjPzuhq27eEn8kRStGS2R-Zf_duh
"""

import pandas as pd
df = pd.DataFrame ({
                    'Ism': [ 'Xurshidbek', 'Doniyorbek', 'Boboxoja', 'Shoyadbek', 'Xursanali', 'Ibrohim', 'Kamronbek', 'Asadbek', 'Islomjon', 'Olloyor'],
                     'Familiya': ['Odilov', 'Nomonjonov', 'Rahmatxonov', 'Maqsudov', 'Xalimov', 'Burxonov', 'Olimov', 'Xudoyberdiyev', 'Usmonov', 'Ashurboyev'],
                     'Yoshi': ['19','19','20','19','19','19', '20','19', '19', '19'],
                     'Kursi':['2','2','2','2','2','2','2','2','2','2']
                    })
print(df)

df.to_excel('malumot.xlsx', index=False,sheet_name='Sheet')